version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

  producer1:
    build:
      context: .
      dockerfile: src/Producer/Dockerfile
    depends_on:
      - rabbitmq
      - mongodb-producer
    environment:
      RabbitMq__Host: "rabbitmq"
      RabbitMq__User: "user"
      RabbitMq__Password: "password"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"

  producer2:
    build:
      context: .
      dockerfile: src/Producer/Dockerfile
    depends_on:
      - rabbitmq
      - mongodb-producer
    environment:
      RabbitMq__Host: "rabbitmq"
      RabbitMq__User: "user"
      RabbitMq__Password: "password"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
  
  consumer1:
    build:
      context: .
      dockerfile: src/Consumer/Dockerfile
    depends_on:
      - rabbitmq
      - mongodb-consumer
    environment:
      RabbitMq__Host: "rabbitmq"
      RabbitMq__User: "user"
      RabbitMq__Password: "password"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"

  consumer2:
    build:
      context: .
      dockerfile: src/Consumer/Dockerfile
    depends_on:
      - rabbitmq
      - mongodb-consumer
    environment:
      RabbitMq__Host: "rabbitmq"
      RabbitMq__User: "user"
      RabbitMq__Password: "password"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-loadbalancer.conf:/etc/nginx/nginx.conf
    depends_on:
      - producer1
      - producer2
      - consumer1
      - consumer2
  
  mongodb-producer:
    image: mongo:latest
    container_name: mongodb-producer
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=zaq1@WSX
    volumes:
      - mongo-producer-data:/data/db
  
  mongodb-consumer:
    image: mongo:latest
    container_name: mongodb-consumer
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=zaq1@WSX
    volumes:
      - mongo-consumer-data:/data/db
  
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0.0
    ports:
      - "18889"
      - "8080:18888"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

volumes:
  rabbitmq_data:
  mongo-producer-data:
  mongo-consumer-data:
